dist: xenial
services:
    - docker
language: bash
env:
    global:
        - QEMU_VER=v3.1.0-3
        - DOCKER_SERVER=docker.io
        - DOCKER_REPO=$DOCKER_SERVER/multiarch/fedora
    matrix:
        - ARCH=x86_64 QEMU_ARCH= VERSION=29
        - ARCH=aarch64 QEMU_ARCH=aarch64 VERSION=29
        - ARCH=ppc64le QEMU_ARCH=ppc64le VERSION=29
        - ARCH=s390x QEMU_ARCH=s390x VERSION=29

        - ARCH=x86_64 QEMU_ARCH= VERSION=30
        - ARCH=aarch64 QEMU_ARCH=aarch64 VERSION=30
        - ARCH=s390x QEMU_ARCH=s390x VERSION=30

before_install:
    - docker run --rm --privileged multiarch/qemu-user-static:register

script:
    - ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO"

after_success:
    - |
      if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" "$DOCKER_SERVER" && \
              docker push $DOCKER_REPO
      fi
