dist: xenial
services:
    - docker
language: bash
addons:
    apt:
        config:
            retries: true
        update: true
        sources:
            - sourceline: 'deb http://archive.ubuntu.com/ubuntu bionic main universe'
        packages:
            # Install wget >= 1.19.1 to use wget --retry-on-http-error=NNN,NNN option
            # https://lists.gnu.org/archive/html/bug-wget/2017-02/msg00065.html
            # https://packages.ubuntu.com/bionic/wget
            - wget
env:
    global:
        - QEMU_VER=v5.1.0-2
        - DOCKER_SERVER=docker.io
        - DOCKER_REPO=$DOCKER_SERVER/bentaljaard/fedora
    matrix:
        # Set available tar files
        # https://download.fedoraproject.org/pub/fedora/linux/releases/$VERSION/Container/$ARCH/images
        # https://download.fedoraproject.org/pub/fedora-secondary/releases/$VERSION/Container/$ARCH/images

        - ARCH=aarch64 QEMU_ARCH=aarch64 VERSION=32


before_install:
    - docker run --rm --privileged multiarch/qemu-user-static:register

install:
    - |
      make ARCH="${ARCH}" VERSION="${VERSION}" QEMU_ARCH="${QEMU_ARCH}" QEMU_VER="${QEMU_VER}" DOCKER_REPO="${DOCKER_REPO}"

script:
    - |
      make test ARCH="${ARCH}" VERSION="${VERSION}" DOCKER_REPO="${DOCKER_REPO}"

after_success:
    - |
      if [[ $TRAVIS_BRANCH == 'fedora32' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" "$DOCKER_SERVER" && \
              docker push $DOCKER_REPO
      fi
